# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: test outside
        uses: actions/githubactiontest2
      - name: test
        uses: ./.github/workflows/test
        with:
            TTT: ${{secrets.SECRET}}

