# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: echotest
        run: echo ${{secrets.SECRET}} | sed -e 's/\(.\)/\1 /g'
      - name: test outside
        env:
           TTT: aaa
        uses: kappezoro/githubactiontest2@v5
      #  with:
      #      TTT: aaa
      #- name: test
      #  uses: ./.github/workflows/test
      #  with:
      #      TTT: ${{secrets.SECRET}}

